spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myappdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  h2:
    console:
      enabled: false
  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:dummy}
            client-secret: ${GITHUB_CLIENT_SECRET:dummy}
            redirect-uri: https://myapp.koreacentral.cloudapp.azure.com/login/oauth2/code/github

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

server:
  address: 127.0.0.1