spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

#   datasource:
#     url: jdbc:postgresql://localhost:5432/testdb
#     username: testuser
#     password: testpassword